// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sastzgwnlitopskrwcvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhc3R6Z3dubGl0b3Bza3J3Y3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDM5MzYsImV4cCI6MjA2NzA3OTkzNn0.tL_leqlqnMG5PkKm8yJ5lhhfT6eTA9sMA9PH7oYvw90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});